#!/bin/bash
#BSUB -J gene_annotation_search                           # Job name
#BSUB -P acc_DiseaseGeneCell   # allocation account
#BSUB -q express                                  # queue
#BSUB -n 1                                            # number of compute cores = 1
#BSUB -R rusage[mem=8000]              # 8GB of memory
#BSUB -W 02:00                                   # walltime in HH:MM
#BSUB -o %J.log                              # output log (%J : JobID)
#BSUB -eo %J.stderr                             # error log

./gene_search.sh BRCA2
