#!/bin/bash
#BSUB -J createGeneVep                           # Job name
#BSUB -P acc_DiseaseGeneCell   # allocation account
#BSUB -q premium                                  # queue
#BSUB -n 8                                            # number of compute cores = 1
#BSUB -R rusage[mem=80000]              # 80GB of memory
#BSUB -W 15:00                                   # walltime in HH:MM
#BSUB -o %J.log                              # output log (%J : JobID)
#BSUB -eo %J.stderr                             # error log

~/github/ArchitectureOfCancer/qsubs/run_create_gene_vep_df.sh ~/github/ArchitectureOfCancer/gene_list.txt
